spring:
  config:
    import: optional:file:backend/.env[.properties]
  datasource:
    url: jdbc:mariadb://localhost:3306/thereabout

thereabout:
  import:
    import-folder: /Users/thwi/git/thereabout/private-test-data